In [2]:
import pandas as pd
import numpy as np

In [5]:
from sklearn import preprocessing
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [6]:
dia = pd.read_csv('C:/Users/ralph/Downloads/dia - diabetes_data_upload.csv')
dia.head()

Age Gender Polyuria Polydipsia sudden weight loss weakness Obesity  \
0   40   Male       No        Yes                 No      Yes     Yes   
1   58   Male       No         No                 No      Yes      No   
2   41   Male      Yes         No                 No      Yes      No   
3   45   Male       No         No                Yes      Yes      No   
4   60   Male      Yes        Yes                Yes      Yes     Yes   

      class  
0  Positive  
1  Positive  
2  Positive  
3  Positive  
4  Positive

In [7]:
dia.describe()

Age
count  520.000000
mean    48.028846
std     12.151466
min     16.000000
25%     39.000000
50%     47.500000
75%     57.000000
max     90.000000

In [8]:
dia.dtypes

Age                    int64
Gender                object
Polyuria              object
Polydipsia            object
sudden weight loss    object
weakness              object
Obesity               object
class                 object
dtype: object

In [12]:
n_dia = LabelEncoder()
dia['Gender'] = n_dia.fit_transform(dia['Gender'].astype('str')) 
dia['Polyuria'] = n_dia.fit_transform(dia['Polyuria'].astype('str')) 
dia['Polydipsia'] = n_dia.fit_transform(dia['Polydipsia'].astype('str')) 
dia['sudden weight loss'] = n_dia.fit_transform(dia['sudden weight loss'].astype('str')) 
dia['weakness'] = n_dia.fit_transform(dia['weakness'].astype('str')) 
dia['Obesity'] = n_dia.fit_transform(dia['Obesity'].astype('str')) 
dia['class'] = n_dia.fit_transform(dia['class'].astype('str')) 
dia.head()

Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  Obesity  \
0   40       1         0           1                   0         1        1   
1   58       1         0           0                   0         1        0   
2   41       1         1           0                   0         1        0   
3   45       1         0           0                   1         1        0   
4   60       1         1           1                   1         1        1   

   class  
0      1  
1      1  
2      1  
3      1  
4      1

In [14]:
x = dia.iloc[:, :-1].values
y = dia.iloc[:, 7]
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
515    1
516    1
517    1
518    0
519    0
Name: class, Length: 520, dtype: int32


In [16]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

In [18]:
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [24]:
# 6 Algorithms for Base Classification
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier

In [22]:
# 1st Algorithm: DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(x_train, y_train)
pred_dt = dt.predict(x_test)
print(y_test)
print(pred_dt)
print(metrics.accuracy_score(y_test, pred_dt)*100)
print(confusion_matrix(y_test, pred_dt))
print(classification_report(y_test, pred_dt))

396    0
367    1
41     1
500    1
497    0
      ..
302    1
172    1
202    0
139    1
359    1
Name: class, Length: 156, dtype: int32
[0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 1 0 1 0 1 1 0 0 1 0 1 1 1 0 1 1 1 0 0 0 0
 1 0 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 0 1 0 1 1 1 1 1 1 1 0 0 1 1
 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 0 1 1 0 0 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 0
 0 1 1 0 0 0 1 0 0 1 1 1 0 1 1 0 1 1 0 1 1 1 0 1 0 1 1 0 0 0 0 1 1 0 0 1 1
 1 1 0 1 1 0 1 1]
94.23076923076923
[[50  6]
 [ 3 97]]
              precision    recall  f1-score   support

           0       0.94      0.89      0.92        56
           1       0.94      0.97      0.96       100

    accuracy                           0.94       156
   macro avg       0.94      0.93      0.94       156
weighted avg       0.94      0.94      0.94       156



In [49]:
# 2nd Algorithm: GaussianNB
nb = GaussianNB()
nb.fit(x_train, y_train)
pred_nb = nb.predict(x_test)
print(y_test)
print(pred_nb)
print(metrics.accuracy_score(y_test, pred_nb)*100)
print(confusion_matrix(y_test, pred_nb))
print(classification_report(y_test, pred_nb))

396    0
367    1
41     1
500    1
497    0
      ..
302    1
172    1
202    0
139    1
359    1
Name: class, Length: 156, dtype: int32
[0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0
 1 0 1 1 1 0 1 0 1 1 1 1 1 0 0 1 1 1 1 1 0 0 0 1 1 0 1 1 1 1 1 0 0 1 0 1 0
 1 1 1 0 1 0 1 1 1 0 1 1 1 0 1 0 0 1 0 1 0 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 0
 0 1 1 0 1 0 1 0 0 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 0 1 1 1 0 0 1 1
 1 1 0 1 1 0 1 1]
85.8974358974359
[[40 16]
 [ 6 94]]
              precision    recall  f1-score   support

           0       0.87      0.71      0.78        56
           1       0.85      0.94      0.90       100

    accuracy                           0.86       156
   macro avg       0.86      0.83      0.84       156
weighted avg       0.86      0.86      0.86       156



In [32]:
# 3rd Algorithm: Logistic Regression
lr = LogisticRegression()
lr.fit(x_train, y_train)
pred_lr = lr.predict(x_test)
print(y_test)
print(pred_lr)
print(metrics.accuracy_score(y_test, pred_lr)*100)
print(confusion_matrix(y_test, pred_lr))
print(classification_report(y_test, pred_lr))

396    0
367    1
41     1
500    1
497    0
      ..
302    1
172    1
202    0
139    1
359    1
Name: class, Length: 156, dtype: int32
[0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 1 0 1 0 1 1 0 0 1 0 1 1 1 0 1 1 1 0 0 0 0
 1 0 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 0 1 0 1 1 1 1 1 1 1 0 0 1 1
 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 0 1 1 0 0 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 0
 0 1 1 0 0 0 1 0 0 1 1 1 0 1 1 0 1 1 0 1 1 1 0 1 0 1 1 0 0 0 0 1 1 0 0 1 1
 1 1 0 1 1 0 1 1]
94.23076923076923
[[50  6]
 [ 3 97]]
              precision    recall  f1-score   support

           0       0.94      0.89      0.92        56
           1       0.94      0.97      0.96       100

    accuracy                           0.94       156
   macro avg       0.94      0.93      0.94       156
weighted avg       0.94      0.94      0.94       156



In [50]:
# 4th Algorithm: KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(x_train, y_train)
pred_knn = knn.predict(x_test)
print(y_test)
print(pred_knn)
print(metrics.accuracy_score(y_test, pred_knn)*100)
print(confusion_matrix(y_test, pred_knn))
print(classification_report(y_test, pred_knn))

396    0
367    1
41     1
500    1
497    0
      ..
302    1
172    1
202    0
139    1
359    1
Name: class, Length: 156, dtype: int32
[0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 1 1 0 1 1 1 0 0 0 0
 1 0 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 0 0 0 1 1 0 1 1 0 0 1 0 1 1
 1 1 1 0 0 1 1 1 1 0 1 1 1 0 1 0 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 0 1 1 0
 0 1 1 0 0 0 1 0 0 1 1 0 0 1 1 0 1 1 0 1 1 1 1 1 1 1 1 0 1 0 0 1 1 0 0 1 1
 1 1 0 1 0 0 1 1]
92.94871794871796
[[51  5]
 [ 6 94]]
              precision    recall  f1-score   support

           0       0.89      0.91      0.90        56
           1       0.95      0.94      0.94       100

    accuracy                           0.93       156
   macro avg       0.92      0.93      0.92       156
weighted avg       0.93      0.93      0.93       156



In [51]:
# 5th Algorithm: Support Vector Classifier
svm = SVC()
svm.fit(x_train, y_train)
pred_svm = svm.predict(x_test)
print(y_test)
print(pred_svm)
print(metrics.accuracy_score(y_test, pred_svm)*100)
print(confusion_matrix(y_test, pred_svm))
print(classification_report(y_test, pred_svm))

396    0
367    1
41     1
500    1
497    0
      ..
302    1
172    1
202    0
139    1
359    1
Name: class, Length: 156, dtype: int32
[0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 1 1 0 1 1 1 0 0 0 0
 1 0 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 1 1
 1 1 1 0 0 1 1 1 1 0 1 1 1 0 1 0 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 0
 0 1 1 0 0 0 1 0 0 1 1 0 0 1 1 0 1 1 0 1 1 1 1 1 1 1 1 0 1 0 0 1 1 0 0 1 1
 1 1 0 1 1 0 1 1]
93.58974358974359
[[50  6]
 [ 4 96]]
              precision    recall  f1-score   support

           0       0.93      0.89      0.91        56
           1       0.94      0.96      0.95       100

    accuracy                           0.94       156
   macro avg       0.93      0.93      0.93       156
weighted avg       0.94      0.94      0.94       156



In [39]:
# 6th Algorithm: Neural Networks
nn = MLPClassifier(hidden_layer_sizes =(200, 200, 200), activation = 'relu', max_iter = 100)
nn.fit(x_train, y_train)
pred_nn = dt.predict(x_test)
print(y_test)
print(pred_nn)
print(metrics.accuracy_score(y_test, pred_nn)*100)
print(confusion_matrix(y_test, pred_nn))
print(classification_report(y_test, pred_nn))

396    0
367    1
41     1
500    1
497    0
      ..
302    1
172    1
202    0
139    1
359    1
Name: class, Length: 156, dtype: int32
[0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 1 0 1 0 1 1 0 0 1 0 1 1 1 0 1 1 1 0 0 0 0
 1 0 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 0 1 0 1 1 1 1 1 1 1 0 0 1 1
 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 0 1 1 0 0 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 0
 0 1 1 0 0 0 1 0 0 1 1 1 0 1 1 0 1 1 0 1 1 1 0 1 0 1 1 0 0 0 0 1 1 0 0 1 1
 1 1 0 1 1 0 1 1]
94.23076923076923
[[50  6]
 [ 3 97]]
              precision    recall  f1-score   support

           0       0.94      0.89      0.92        56
           1       0.94      0.97      0.96       100

    accuracy                           0.94       156
   macro avg       0.94      0.93      0.94       156
weighted avg       0.94      0.94      0.94       156



D:\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


In [45]:
# Additonal Algorithms
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [58]:
# 6th Algorithm: Random Forest Classifier
rf = RandomForestClassifier()
rf.fit(x_train, y_train)
pred_rf = rf.predict(x_test)
print(y_test)
print(pred_svm)
print(metrics.accuracy_score(y_test, pred_rf)*100)
print(confusion_matrix(y_test, pred_rf))
print(classification_report(y_test, pred_rf))

396    0
367    1
41     1
500    1
497    0
      ..
302    1
172    1
202    0
139    1
359    1
Name: class, Length: 156, dtype: int32
[0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 1 1 0 1 1 1 0 0 0 0
 1 0 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 1 1
 1 1 1 0 0 1 1 1 1 0 1 1 1 0 1 0 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 0
 0 1 1 0 0 0 1 0 0 1 1 0 0 1 1 0 1 1 0 1 1 1 1 1 1 1 1 0 1 0 0 1 1 0 0 1 1
 1 1 0 1 1 0 1 1]
96.7948717948718
[[52  4]
 [ 1 99]]
              precision    recall  f1-score   support

           0       0.98      0.93      0.95        56
           1       0.96      0.99      0.98       100

    accuracy                           0.97       156
   macro avg       0.97      0.96      0.96       156
weighted avg       0.97      0.97      0.97       156



In [59]:
# 7th Algorithm: Gradient Boosting Classifier
gb = GradientBoostingClassifier()
gb.fit(x_train, y_train)
pred_gb = gb.predict(x_test)
print(y_test)
print(pred_gb)
print(metrics.accuracy_score(y_test, pred_gb)*100)
print(confusion_matrix(y_test, pred_gb))
print(classification_report(y_test, pred_gb))

396    0
367    1
41     1
500    1
497    0
      ..
302    1
172    1
202    0
139    1
359    1
Name: class, Length: 156, dtype: int32
[0 1 1 1 0 1 0 0 0 1 1 1 1 1 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 0 1 1 1 0 0 0 0
 1 0 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 0 0 1 0 1 1 0 1 1 0 0 0 0 1 1
 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 0 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 0
 0 1 1 0 0 0 1 0 0 1 1 1 0 1 1 0 1 1 0 1 1 1 0 1 0 1 1 0 1 0 0 1 1 0 0 1 1
 1 1 0 1 1 0 1 1]
95.51282051282051
[[53  3]
 [ 4 96]]
              precision    recall  f1-score   support

           0       0.93      0.95      0.94        56
           1       0.97      0.96      0.96       100

    accuracy                           0.96       156
   macro avg       0.95      0.95      0.95       156
weighted avg       0.96      0.96      0.96       156

